name: Deploy to DigitalOcean via OpenTofu

on:
  push:
    branches: [main]

jobs:
  plan-and-apply:
    runs-on: ubuntu-latest
    concurrency:
      group: webapp-iac
      cancel-in-progress: true

    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_ssh_fingerprint: ${{ secrets.DO_SSH_FP }}
      TF_VAR_repo_url: "https://github.com/<your-user>/<repo>.git"
      TF_VAR_git_branch: "main"
      # Remove the next two if you skipped the Spaces backend
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
      TF_IN_AUTOMATION: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.6.2"

      - name: Init
        working-directory: infra
        run: tofu init -input=false

      - name: Plan
        working-directory: infra
        run: tofu plan -out=plan.out

      - name: Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra
        run: tofu apply -input=false -auto-approve plan.out
